## 실전문제(2) 위에서 아래로

In [7]:
n = int(input())
array = []
for i in range(n):
    array.append(int(input()))

array = sorted(array,reverse=True)

for i in array:
    print(i, end= " ")

 3
 15
 27
 12


27 15 12 

## 실전문제(3) 성적이 낮은 순서로 학생 출력하기

In [10]:
n = int(input())
array = []
for i in range(n):
    data = input().split()
    array.append((data[0],int(data[1])))

array = sorted(array, key = lambda x: x[1])

for i in array:
    print(i[0], end=" ")

 2
 홍길동 95
 이순신 77


이순신 홍길동 

## 실전문제(4) 두 배열의 원소 교체

In [11]:
n, k = map(int, input().split())
a = list(map(int,input().split()))
b = list(map(int,input().split()))

a.sort()
b.sort(reverse=True)

for i in range(k):
    if a[i]<b[i]:
        a[i],b[i] = b[i],a[i]
    else:
        break

print(sum(a))

 5 3
 1 2 5 4 3
 5 5 6 6 5


26


## 기출문제(23) 국영수

In [35]:
n = int(input())
array = []
for i in range(n):
    data = input().split()
    array.append((data[0],int(data[1]),int(data[2]),int(data[3])))

array = sorted(array,key=lambda x: (-x[1],x[2],-x[3],x[0]))

for i in array:
    print(i[0])

KeyboardInterrupt: Interrupted by user

## 기출문제(24) 안테나

In [7]:
n = int(input())
array = list(map(int,input().split()))
array.sort()

length = len(array)
result = int(array[0] + (array[-1]-array[0])/2)

print(result)

 4
 5 1 7 9


5


## 기출문제(25) 실패율

In [31]:
import numpy as np
def solution(N, stages):
    temp = []
    answer =[]
    
    stage_y = np.zeros(N+1)
    stage_n = np.zeros(N+2)

    for i in stages:
        stage_y[:i+1] += 1
        stage_n[i] += 1
        
    stage_y = stage_y[1:]
    stage_n = stage_n[1:-1]
        
    key = [n/y for n,y in zip(stage_n,stage_y)]
    print(key)
    
    
    for i in range(len(key)):
        if key[i] == np.inf:
            key[i] = 0
        temp.append((i+1,key[i]))
    
    temp = sorted(temp,key=lambda x: (-x[1],x[0]))
        
    for i in temp:
        answer.append(i[0])
    
    return answer

solution(5,[2, 1, 2, 6, 2, 4, 3, 3])

[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0.]
[2. 2. 1. 0. 0. 0.]
[0. 1. 1. 0. 0. 0. 0.]
[3. 3. 2. 0. 0. 0.]
[0. 1. 2. 0. 0. 0. 0.]
[4. 4. 3. 1. 1. 1.]
[0. 1. 2. 0. 0. 0. 1.]
[5. 5. 4. 1. 1. 1.]
[0. 1. 3. 0. 0. 0. 1.]
[6. 6. 5. 2. 2. 1.]
[0. 1. 3. 0. 1. 0. 1.]
[7. 7. 6. 3. 2. 1.]
[0. 1. 3. 1. 1. 0. 1.]
[8. 8. 7. 4. 2. 1.]
[0. 1. 3. 2. 1. 0. 1.]
[8. 7. 4. 2. 1.]
[1. 3. 2. 1. 0.]
[0.125, 0.42857142857142855, 0.5, 0.5, 0.0]
[(1, 0.125), (2, 0.42857142857142855), (3, 0.5), (4, 0.5), (5, 0.0)]
! [(3, 0.5), (4, 0.5), (2, 0.42857142857142855), (1, 0.125), (5, 0.0)]


[3, 4, 2, 1, 5]

In [20]:
np.inf

inf